apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: spin-{{ name }}
  namespace: {{ namespace }}
  annotations:
    moniker.spinnaker.io/application: '"spin"'
    moniker.spinnaker.io/cluster: '"{{ name }}"'
  labels:
    app: spin
    cluster: spin-{{ name }}
spec:
  serviceName: spin-{{ name }}
  replicas: {{ replicas }}
  selector:
    matchLabels:
      app: spin
      cluster: spin-{{ name }}
  template:
    metadata:
      annotations: {
      {% for key, value in podAnnotations.items() %}
              "{{ key }}" : "{{ value }}"{% if not loop.last %}, {% endif %}
      {% endfor %}}
      labels:
        app: spin
        cluster: spin-{{ name }}
    spec: {{ podSpec }}
